# Generated by Django 4.2.4 on 2023-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('poster_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('spoken_languages', models.CharField(blank=True, max_length=255, null=True)),
                ('made_in', models.CharField(blank=True, max_length=255, null=True)),
                ('directors', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('popularity', models.DecimalField(blank=True, decimal_places=12, max_digits=18, null=True)),
                ('premiere_date', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('stroer_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
