# Generated by Django 4.2.4 on 2023-08-31 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='photo_file_name',
            new_name='person_photo_file_name',
        ),
    ]
