# Generated by Django 4.2.4 on 2023-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_people_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='trailer_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
