# Generated by Django 4.2.4 on 2023-09-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movies_trailer_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='character_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='people',
            name='person_photo_file_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='role',
        ),
        migrations.RemoveField(
            model_name='people',
            name='stroer_id',
        ),
        migrations.AddField(
            model_name='people',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='deathday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MoviesPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('person_photo_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('character_name', models.CharField(blank=True, max_length=255, null=True)),
                ('stroer_id', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='movies.movies')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_people', to='movies.people')),
            ],
        ),
    ]
